Everyone is advanced
getditto/docs pull request #143
Opened 2022-03-10 19:29 UTC by okdistribute

Right now, the "Advanced" category is a catch-all for various topics. It makes it difficult to find something specific. 

I reduced 'Advanced' into 'How it works', and then re-filed many of the resulting pages into their appropriate places in the documentation. 

For example, anything platform installation related went into the appropriate Installation section, which reorganizes the 'Advanced->Platform Permissions' section to be available to the reader when that information is relevant. 

![Screen Shot 2022-03-10 at 11 27 42 AM](https://user-images.githubusercontent.com/633012/157739764-29a45fe5-caed-4f8d-b733-8d7c9c74bf67.png)

![Screen Shot 2022-03-10 at 11 27 46 AM](https://user-images.githubusercontent.com/633012/157739765-48eea7e6-e70c-4ce4-b84f-6aac49dace16.png)

![Screen Shot 2022-03-10 at 11 27 38 AM](https://user-images.githubusercontent.com/633012/157739758-111401c5-cc1d-4d80-835d-65a3e085370c.png)
.

2022-03-11 00:56 UTC, phatblat requested changes

2022-03-11 08:11 UTC, thombles approved these changes
Nice! The write-up about identity types is particularly thorough. I've left a number of suggestions but I'll leave it to your best judgement.

2022-03-11 08:11 UTC, thombles commented on docs/tutorials/security/3-login.mdx
> +a new `ObservedObject` that we can subscribe to for updates to the
Possibly `ObservableObject` was meant here? Not 100% sure

2022-03-11 08:11 UTC, thombles commented on docs/tutorials/security/3-login.mdx
> +                authenticationDelegate: AuthDelegate(token: accessToken)
🤔  Delegates are generally held only weakly, meaning it must be stored somewhere by the caller to avoid being deallocated. Is that dealloc happening here after the creation of `Ditto`?

2022-03-11 08:11 UTC, thombles commented on docs/tutorials/security/3-login.mdx
> +To make this usable for real-world applications, you can retreieve the user's
```suggestion
To make this usable for real-world applications, you can retrieve the user's
```

2022-03-11 21:56 UTC, okdistribute commented on docs/concepts/network.mdx
> +ditto.tryStartSync();
Oh what doesn't exist yet? I just copy-pasted this from the existing docs

2022-03-11 21:59 UTC, okdistribute commented on docs/tutorials/security/3-login.mdx
> +                authenticationDelegate: AuthDelegate(token: accessToken)
I have no idea! I don't fully understand how this works and the implications of it, I haven't used much swift. -- @phatblat, ideas?

2022-03-11 21:59 UTC, okdistribute commented on docs/tutorials/security/3-login.mdx
> +a new `ObservedObject` that we can subscribe to for updates to the
Yes good point

2022-03-11 22:01 UTC, okdistribute commented on docs/tutorials/security/3-login.mdx
> +a new `ObservedObject` that we can subscribe to for updates to the
I copy-pasted this from the demo app which seems to work

2022-03-11 22:01 UTC, okdistribute commented on docs/tutorials/security/3-login.mdx
> +a new `ObservedObject` that we can subscribe to for updates to the
https://github.com/getditto/demo-apps/pull/275/files#diff-e5762adbe258b648227d48657b28d86968c01a54a4d7132ae44212d57671330aR123

2022-03-11 22:02 UTC, okdistribute commented on docs/concepts/network.mdx
> +ditto.tryStartSync()
Hmm good point, but maybe we can open a separate PR about this whole page. I feel like it needs improvement generally and I copy/pasted it

2022-03-11 22:08 UTC, okdistribute commented on docs/security/online-with-authentication/designing-permissions.mdx
> +          "endsWith(_id.title, 'Potter')"
Good catch

2022-03-12 00:56 UTC, okdistribute commented on docs/tutorials/security/3-login.mdx
> +                authenticationDelegate: AuthDelegate(token: accessToken)
(I removed the tutorial from this PR, that was an accident)

2022-03-12 01:14 UTC, merged