Add initial experimental bus docs for Swift
getditto/docs pull request #466
Opened 2023-02-18 02:38 UTC by skylerjokiel

Adding some initial docs so we can share with customers.

2023-02-18 02:45 UTC, okdistribute requested changes

2023-02-18 02:45 UTC, okdistribute commented on snippets.json
> +    "bus-single-message-receive": "// User2 sets up a delegate to handle inbound requests\nditto.bus.delegate = SingleMessageReceivedDelegate()\n\nclass SingleMessageReceivedDelegate: DittoBusDelegat
The snippets are automatically generated from the monorepo so these will get overwritten when v4 is released. 

Do you have a corresponding PR to the monorepo that can generate these snippets? @texasRanger09 knows how to do this and can help you if you need assistance

2023-02-18 02:46 UTC, okdistribute requested changes

2023-02-18 02:46 UTC, okdistribute commented on docs/common/sidebar.js
> +        label: "Experimental",
If this is only available for iOS and Android we should probably hide it on the other language sidebars

2023-02-18 02:48 UTC, skylerjokiel commented on docs/common/sidebar.js
> +        label: "Experimental",
Agreed.

With this change it will only show up for languages that have experimental folder. Currently I only added docs for iOS.

2023-02-18 02:48 UTC, skylerjokiel commented on snippets.json
> +    "bus-single-message-receive": "// User2 sets up a delegate to handle inbound requests\nditto.bus.delegate = SingleMessageReceivedDelegate()\n\nclass SingleMessageReceivedDelegate: DittoBusDelegat
Terrific! Because doing this by hand sucked lol

2023-02-18 02:49 UTC, skylerjokiel commented on docs/common/sidebar.js
> +        label: "Experimental",
You can check it on the sample site. If you want me to do it a different way let me know.

2023-02-20 16:34 UTC, phatblat commented on snippets.json
> +    "bus-single-message-receive": "// User2 sets up a delegate to handle inbound requests\nditto.bus.delegate = SingleMessageReceivedDelegate()\n\nclass SingleMessageReceivedDelegate: DittoBusDelegat
Do we have the doc snippets update process in Notion anywhere? I was thinking links to where those tests live across the monorepo would be helpful

2023-02-21 18:40 UTC, okdistribute commented on snippets.json
> +    "bus-single-message-receive": "// User2 sets up a delegate to handle inbound requests\nditto.bus.delegate = SingleMessageReceivedDelegate()\n\nclass SingleMessageReceivedDelegate: DittoBusDelegat
No, I didn't do that because I figured it could change and it's easy to look up the string `@ditto/snippet-start` to find all snippets.

We have a video that we use to train folks on this https://www.loom.com/share/32a5428c2e7e49469a87e6d0b9e0a3d2

2023-02-21 18:42 UTC, okdistribute commented
@skylerjokiel , I want to remove the `snippets.json` changes and replace it with ones genuinely generated from the latest monorepo, but you have this on a fork so I can't do it myself.

2023-02-21 22:59 UTC, okdistribute approved these changes

2023-02-21 23:35 UTC, merged