[WIP] Added developer FAQ and collection architecture pages
getditto/docs pull request #467
Opened 2023-02-18 04:46 UTC by kndoshn

Closes #432

2023-02-18 08:03 UTC, okdistribute requested changes

2023-02-18 08:03 UTC, okdistribute commented on docs/common/sidebar.js
> +      "common/development-frequently-asked-questions",
We have a troubleshooting page already, can we combine these?

2023-02-18 11:22 UTC, kndoshn commented on docs/common/sidebar.js
> +      "common/development-frequently-asked-questions",
I think developers don't look at the troubleshooting page until they notice a trouble, and I think what we want to provide now is a way to prevent troubles.

Developers have contacted us when they have problems, and we have worked with them to solve them, but we want to prevent the problems from happeneing as much as possible.

I hope we have pages on our docs developers visit on earlier phase of development. I think we could have better names than the ones I have on this PR, though.

So I thought it would be better to separate troubleshootings and these pages. What do you think?

2023-02-18 11:56 UTC, kndoshn commented on docs/common/sidebar.js
> +      "common/development-frequently-asked-questions",
Maybe I shouldn't have made the page "FAQ" style because it does look like a troubleshooting...

2023-02-18 16:41 UTC, okdistribute commented on docs/common/sidebar.js
> +      "common/development-frequently-asked-questions",
How about the tutorial?

2023-02-21 19:26 UTC, okdistribute commented on docs/common/collection-architectures.md
> +There are several ways you can do to separate sync groups:
Let's not use the word 'sync groups' because we also have a `syncGroup` feature :P I'm not sure of a better word here but let's think on it @abunur @magicwave

2023-02-21 19:27 UTC, okdistribute commented on docs/common/collection-architectures.md
> +title: 'Collection architectures'
Great doc! Can we put it in the `schemas` page? That page only has information about versioning, but before versioning your docs you have to define what they contain!

I'm thinking that the Schema section should probably be in the bottom of the 'Getting Started' section as well.

2023-02-21 19:28 UTC, okdistribute commented on docs/common/collection-architectures.md
> +// TODO: description
If you agree to moving this to the 'schema' page I can take a pass at these descriptions and reasons by next week

2023-02-21 19:28 UTC, okdistribute commented on docs/common/development-frequently-asked-questions.md
> +## Which Identity should I use to initialize Ditto?
Some of these will be in the troubleshooting.mdx and some of them should be in the respective pages near where the concept is introduced.

2023-02-21 20:47 UTC, magicwave commented on docs/common/collection-architectures.md
> +There are situations where you want to sync specific only for a part of a model.
Should be "... where you want to sync **specifically** only for..."?

2023-02-21 21:54 UTC, okdistribute commented on docs/common/collection-architectures.md
> +There are several ways you can do to separate sync groups:
Well actually we might want to use the work 'sync groups' if in the same breath we will recommend that they use the syncGroup transport config!

2023-02-22 08:35 UTC, kndoshn commented on docs/common/collection-architectures.md
> +There are several ways you can do to separate sync groups:
`syncGroup` is set on the Ditto instance, but customers often ask about using multiple different groups in their app.

For instance, they want to share all meals data across all crews on the flight, and some data is shared only between chiefs. Also they usually don't want to sync data between different flights, but some data has to be synced with other flights.

2023-02-23 01:25 UTC, abunur requested changes

2023-02-23 01:25 UTC, abunur commented on docs/common/collection-architectures.md
> +There are situations where you want to sync specific only for a part of a model.
What does "model" in this context refer to specifically? From the code examples below it seems to be the data model as described by the developer consuming the SDK, correct? i.e. the swift struct as shown below or a Kotlin data class, or Java POJO

2023-02-23 01:25 UTC, abunur commented on docs/common/collection-architectures.md
> +/// This doesn't contan information that is not modified by users
I would remove the double negative here and rephrase, e.g.

"This contains information that is not modified by users" 

(this is the exact opposite meaning, so please confirm what you meant here

2023-02-23 01:25 UTC, abunur commented on docs/common/development-frequently-asked-questions.md
> +## Which Identity should I use to initialize Ditto?
We can also cross-link between, e.g. if we have a tutorial providing a detailed example, it should be linked from the troubling shooting page etc. Similar to how Google will provide a link to a CodeLab directly from documentation

2023-02-23 01:25 UTC, abunur commented on docs/common/sidebar.js
> +      "common/development-frequently-asked-questions",
Yes we should review these when writing the tutorials and provide links to the tutorials from these as well. Also I think it might be helpful to have @magicwave review this page, as he has gone much deeper in the woods with the Ditto queries on iOS than I have on Android so far.

2023-02-23 13:20 UTC, kndoshn commented
@okdistribute @magicwave @abunur
I moved contentes to under `Schemas`, `Documents`, `Syncing`, and `Troubleshooting`.

There're still a lot of TODOs, but editing, adding, or suggestions are very welcome!

2023-02-27 19:16 UTC, magicwave commented on docs/common/concepts/syncing-data.mdx
> +subscriptions.removeAll() // After calling cancel, it is safe to remove them.
I don't know the answer to this, but it seems that if we have a `subscriptions.removeAll()`, which I assume the SDK offers as a convenience API, yet we shouldn't call it until we have looped through the collection ("collection" in Swift language semantics, not Ditto), wouldn't we expect to have a `subscriptions.cancelAll()` convenience API, or even `subscriptions.cancelAndRemoveAll()`?

2023-02-27 19:18 UTC, okdistribute commented on docs/common/concepts/syncing-data.mdx
> +subscriptions.removeAll() // After calling cancel, it is safe to remove them.
`subscriptions.removeAll()` is a Swift-specific thing for arrays. This should be made SDK-specific

2023-02-27 20:08 UTC, magicwave commented on docs/common/concepts/syncing-data.mdx
> +subscriptions.removeAll() // After calling cancel, it is safe to remove them.
Oh ok. If I understand you, I assumed subscriptions.removeAll() is an SDK method but in fact it's just an example of removing all subscription objects in a Swift collection? Makes sense, my bad.

2023-02-27 20:36 UTC, okdistribute commented on docs/common/concepts/syncing-data.mdx
> +subscriptions.removeAll() // After calling cancel, it is safe to remove them.
That's right. The fact that you were confused though means we need to change this example because it won't be clear to readers

2023-03-07 01:59 UTC, okdistribute commented
I'm going to go through and finish this out. Opened a separate ticket to get snippets for find_by_id https://github.com/getditto/ditto/issues/7831

2023-03-07 02:32 UTC, okdistribute requested changes

2023-03-07 02:32 UTC, okdistribute commented on docs/common/concepts/schemas.mdx
> +### Complex patterns
TODO: Better title/more info here

2023-03-08 23:17 UTC, okdistribute commented
This is ready again for review @abunur @magicwave

2023-03-09 15:09 UTC, abunur approved these changes
LGTM 👍🏽🚀

2023-03-09 21:50 UTC, merged

2023-03-14 20:54 UTC, magicwave commented on docs/common/concepts/documents.mdx
> +While it is typically common for all documents
this is nitpicking: "typically common" is redundant; we could prefer "While it is typical for all documents...", or "While it is common for all documents..."

2023-03-14 21:27 UTC, magicwave commented on docs/common/concepts/schemas.mdx
> +Ditto breaks a document into chunks, synchronize those parts over the mesh, and
"synchronize" should be "synchronizes".

2023-03-14 21:32 UTC, magicwave commented on docs/common/concepts/syncing-data.mdx
> +## How can I stop to subscribing data?
"How can I stop to subscribing data?" should be "How can I stop subscribing to data?"

2023-03-14 21:35 UTC, magicwave commented on docs/common/concepts/syncing-data.mdx
> +Ensure that you always `cancel` or `stop` on subscriptions when you no longer
Not sure if my comment here is relevant, but there is no `DittoSubscription.stop()` API in Swift.

2023-03-14 22:02 UTC, okdistribute commented on docs/common/concepts/syncing-data.mdx
> +Ensure that you always `cancel` or `stop` on subscriptions when you no longer
True, it is called `stop` in Android and `cancel` in Swift for #reasons

2023-03-14 22:02 UTC, magicwave commented on docs/common/concepts/syncing-data.mdx
> +subscription is alive. We recommend that you evict data once per day or once per
Is the intent here to advise limited frequency of eviction? If so, maybe we should preface the recommendation for once a day or once a week eviction by saying something like, "Data should not be evicted excessively frequently ...[maybe with explanation of why]".

2023-03-14 22:41 UTC, magicwave commented on docs/common/concepts/syncing-data.mdx
> +## How can I stop to subscribing data?
Oh! dang, sorry...