Update Attachments markdown and snippets
getditto/docs pull request #545
Opened 2023-04-25 22:02 UTC by magicwave

2023-04-26 17:44 UTC, okdistribute commented
Great Eric, thanks for this. Is this PR related to this one in the ditto monorepo? https://github.com/getditto/ditto/pull/8403 

It looks like you generated the snippets, which is great! Just wondering where those are in the code

2023-04-27 00:56 UTC, okdistribute commented
Looking good!

2023-04-27 01:00 UTC, okdistribute commented on docs/common/datamodel/attachment.mdx
> +devices, then you should use the attachments feature. Any piece of data larger than 250kb should be shared using this `Attachment` type.
Perhaps we want to link here from Schemas where we note "Documents should not be larger than 250Kb. Any document that is larger than 5MB will not synchronize to other peers. Ditto over Bluetooth LE typically synchronizes documents at a maximum speed of 20 kB/second. This means that a single document that is 250kb large could take 10 seconds (in the best case scenario) to synchronize for the first time between devices." thoughts @contenuto ?

2023-04-27 17:10 UTC, okdistribute commented on docs/common/datamodel/attachment.mdx
> +`DittoCollection.fetchAttachment(token:deliverOn:onFetchEvent:)` has been wrapped in an
Not all languages will have this, so we should wrap this section so it only shows up in the [Swift documentation using this method.](https://github.com/getditto/docs/blob/main/docs/common/security/authentication.mdx?plain=1#L57-L115)

I can take a look at this

2023-04-27 17:49 UTC, magicwave commented on docs/common/datamodel/attachment.mdx
> +`DittoCollection.fetchAttachment(token:deliverOn:onFetchEvent:)` has been wrapped in an
Ah, ok, sorry, I thought the whole thing is Swift-specific, but on reflection, that wouldn't make much sense...

2023-04-27 18:27 UTC, okdistribute commented on docs/common/datamodel/attachment.mdx
> +`DittoCollection.fetchAttachment(token:deliverOn:onFetchEvent:)` has been wrapped in an
I'm happy that you started with swift first. All of our docs are cross language right now but eventually we will probably want separate text for each language because it will be a better experience

2023-04-27 20:50 UTC, okdistribute commented on docs/common/datamodel/attachment.mdx
> +`DittoCollection.fetchAttachment(token:deliverOn:onFetchEvent:)` has been wrapped in an
We could also make reference to the following parts of the chat app., eg Creating an attachment: https://github.com/getditto/demoapp-chat/blob/main/iOS/DittoChat/Data/DittoService.swift#L299-L321

2023-04-27 22:43 UTC, magicwave commented on docs/common/datamodel/attachment.mdx
> +`DittoCollection.fetchAttachment(token:deliverOn:onFetchEvent:)` has been wrapped in an
> Not all languages will have this, so we should wrap this section so it only shows up in the [Swift documentation using this method.](https://github.com/getditto/docs/blob/main/docs/common/security/authentication.mdx?plain=1#L57-L115)
> 
> I can take a look at this

I had a go at it but couldn't figure out how to make that happen

2023-05-02 23:02 UTC, contenuto requested changes
Hi Eric, 
I learned a lot about Swift today. I hope I'm on the right path here. If I'm incorrect, please call me out so I can learn. If you want to chat about this review, let me know.  Thanks!

2023-05-02 23:02 UTC, contenuto commented on docs/common/datamodel/attachment.mdx
> +
```suggestion
Since the attachment fetcher must remain a globally available instance for the entire duration of the asynchronous fetch operation, we maintain a strong reference to the attachment fetcher as indicated with a property. 

If, at anytime, the fetcher operation goes out of scope, fetch will be silently aborted.  

```

2023-05-02 23:04 UTC, contenuto commented on docs/common/datamodel/attachment.mdx
> +
Should this be "...peer-to-peer sync and mesh performance..."?

2023-05-02 23:08 UTC, contenuto commented on docs/common/datamodel/attachment.mdx
> +
The "if already fetched" bit is confusing me. Shouldn't this be "if already fetched and initialized, the Small Peer in-memory database..." or something?

2023-05-02 23:12 UTC, contenuto commented on docs/common/datamodel/attachment.mdx
> +
What happens when fetch ops silently aborts? How do you know? Do you get the print error "Error creating TMP storage directory" or something?

2023-05-02 23:29 UTC, okdistribute commented on docs/common/datamodel/attachment.mdx
> +
The small peer on swift is actually on disk not in memory -- only the JavaScript SDK is in memory (I can see that is likely confusing!)

2023-05-03 13:07 UTC, contenuto commented on docs/common/datamodel/attachment.mdx
> +
Ah, okay. I think it's accurate now. Well, I'm not sure about the "...do not unnecessarily consume the local disk space attached to the Small Peer or, if syncing by way of the mesh, the data transmission rate." I assume so.

2023-05-09 22:37 UTC, okdistribute commented on docs/common/datamodel/attachment.mdx
> +
THat seems right!

2023-05-09 22:38 UTC, okdistribute commented on docs/common/datamodel/attachment.mdx
> +
More accurately, the DittoATtachmentToken would be referenced later. The token is a unique identifier that points to that data somewhere on the mesh

2023-05-11 23:02 UTC, okdistribute commented on docs/common/datamodel/attachment.mdx
> +
Unfortunately we don't have errors :(

2023-05-11 23:03 UTC, okdistribute commented on docs/common/datamodel/attachment.mdx
> +`DittoCollection.fetchAttachment(token:deliverOn:onFetchEvent:)` has been wrapped in an
Taking a look again!

2023-05-11 23:06 UTC, okdistribute commented
Nice edits @contenuto ! Thanks @magicwave for the work putting this together. It's a significant improvement

2023-05-11 23:41 UTC, merged