Add best practices for map type
getditto/docs pull request #556
Opened 2023-05-09 22:35 UTC by okdistribute

### Description

In recent internal conversations, we needed to communicate best practices for updating a map type as part of the documentation. This fixes that omission.

### Checklist

- [x] My code builds clean without any errors or warnings
- [x] I have viewed your page in the netlify preview link (below) and confirmed that there are no broken links
- [x] I have run my changes through a spell checker
- [x] If I changed a link location, I added an entry to the `build/_redirects` file according to the [Netlify specification](https://docs.netlify.com/routing/redirects/redirect-options/)
- [x] I have linked this PR to any existing issue by mentioning the issue in the description body
- [x] I will close any relevant GitHub issues once my PR is merged

2023-05-11 12:34 UTC, contenuto requested changes
A few suggestions for you to consider. Looks good!

2023-05-11 12:34 UTC, contenuto commented on docs/common/datamodel/map.mdx
> +The recommended way to update and add keys within an embedded Map is to use keypath indexing.
Maybe "Use keypath indexing to update and add keys to a map that is nested in another map."

2023-05-11 12:34 UTC, contenuto commented on docs/common/datamodel/map.mdx
> +It is not possible to remove values by simply omitting them from the map.  This is because the values will merge with the existing map in the mesh (subscription server, or even locally on disk). The
Maybe "Values of map properties merge with the existing mesh, regardless if it is a subscription server mesh or local mesh, so simply omitting them from the CRDT map doesn't remove them. Instead, the CRDT map creates an operation for that key and existing keys remain unchanged."

Or something.

2023-05-15 17:15 UTC, okdistribute commented on docs/common/datamodel/map.mdx
> +It is not possible to remove values by simply omitting them from the map.  This is because the values will merge with the existing map in the mesh (subscription server, or even locally on disk). The
Great thanks!

2023-05-15 17:15 UTC, merged